---
title: ""
author: 
  name: "Lisa Avery lisa.avery@uhn.ca"
  institute: "Biostatistics@UHN" 
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    toc: TRUE
  docx:
    fig-height: 4
    fig-width: 6.5
#    reference-doc: 'wordTemplate.docx'
  pdf:
    fig-height: 4
    fig-width: 6.5
#bibliography: bibfile.bib  
editor: source
execute: 
  echo: false
  warning: false
  message: false
knitr:
  opts_chunk: 
    comment: ""
    dpi: 300     
---

```{r setup}
library(tidyverse)
library(devtools)
library(janitor)
library(reportRmd)
load_all()

```

```{r}

```

```{r}

data_file = "/Users/lisaavery/Library/CloudStorage/OneDrive-UHN/Gonzalez/CODED ENDOMETRIAL CANCER DATABASE.xlsx"

data_sheet = "For_import"
dictionary_sheet = "Sheet2"

imported_data <- read_excel_with_dictionary(data_file, data_sheet, dictionary_sheet,dates_as_character=FALSE,na="") 

```

```{r}
data_file = "/Users/lisaavery/Library/CloudStorage/OneDrive-UHN/Diamondis/GliomaGrant/combined_glioma_data_andrew_alizera_ati_9Jul2025.xlsx"

data_sheet = "Sheet 1"
dictionary_sheet = "dict"

imported_data <- read_excel_with_dictionary(data_file, data_sheet, dictionary_sheet,dates_as_character=FALSE,na="") 

```

```{r}
data_file <- "inst/extdata/study_data_messy.xlsx"
file.exists(data_file)
data_sheet="data"
dictionary_sheet = "dict"
dates_as_character=FALSE
na=""


imported_data <- read_excel_with_dictionary(data_file, data_sheet, dictionary_sheet,dates_as_character=FALSE,na="") 
View(imported_data$coded_data)
```

```{r}
updated_filenme <- "R/ALL_ANDREW_CLINICAL_INFORMATION_Mar26.xlsx"
imported <- read_excel_with_dictionary(data_file=updated_filenme,data_sheet="Sheet1",dictionary_sheet = "dict") # updated 26 mar 2025

imported$coded_data$Type

```


```{r}
library(devtools)
load_all()
data_file <- filenm <- "R/Final Excel Spreadsheet PPROM.xlsx"


test <-read_excel_with_dictionary(filenm,data_sheet = "for_import",dictionary_sheet =  "dict")
names(test$coded_data)
```

```{r}
load_all()
data_file <- filenm <- "R/Copy of Sheets_all_collab_data_glioma_LA.xlsx"
data_sheet <-"Alireza_data"
dictionary_sheet <- "Alizera_dict"
dates_as_character=FALSE;na=""

sht_nms <- readxl::excel_sheets(filenm)

alizera_data_import <- importExcel::read_excel_with_dictionary(filenm,sht_nms[1],sht_nms[2])
alizera_data <- alizera_data_import$coded_data

data_file <- filenm <- "R/Copy of Sheets_all_collab_data_glioma_LA.xlsx"
data_sheet <- sht_nms[3]
dictionary_sheet <- sht_nms[4]
ati_xsec_data_import <- read_excel_with_dictionary(filenm,sht_nms[3],sht_nms[4])
ati_xsec_data <- ati_xsec_data_import$coded_data
names(ati_xsec_data)
ati_long_data <- ati_long_data_import$coded_data


ati_xsec_data |> 
  tabyl(IDH1_Status)

ati_xsec_data$IDH1_Status
rm_compactsum(ati_xsec_data,xvars = c(IDH1_Status))
rm_compactsum(ati_xsec_data,xvars = c(Age,Sex))

save(ati_xsec_data, file = "../ati_xsec_data.rda")
```


```{r}
data_file <- "R/ALL_ANDREW_CLINICAL_INFORMATION.xlsx"
data_sheet <-"data"
dictionary_sheet <- "dict"
dates_as_character=FALSE;na=""
andrew_data_import <- read_excel_with_dictionary(data_file,data_sheet="data",dictionary_sheet = "dict")
andrew_data <- andrew_data_import$coded_data
```


```{r}
data_file <- "R/updated_EX-CIPN Data_Mar43.xlsx"
physical_df <- read_excel_with_dictionary(data_file,data_sheet="Physical Assessment",dictionary_sheet = "physical_dictionary")

```

```{r}
current_file <- data_file <- "/Users/lisaavery/Library/CloudStorage/OneDrive-UHN/Kirsch/SARC032_patient_outcomes_2025_03_05_forImport.xlsx"
data_sheet = "for_import"
dictionary_sheet = "dict"
read_excel_with_dictionary(data_file = current_file,
                                        data_sheet = "for_import",
                                        dictionary_sheet = "dict")
```

